# Generated by Django 2.2.12 on 2020-05-09 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('total_num_of_options', models.IntegerField(blank=True)),
                ('last_updated_time', models.TimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default='option statement', max_length=200)),
                ('creation_time', models.TimeField(auto_now_add=True)),
                ('modified_time', models.TimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Questions')),
            ],
            options={
                'ordering': ['-modified_time'],
                'unique_together': {('statement', 'question')},
            },
        ),
    ]
