# Generated by Django 2.2.12 on 2020-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='total_num_of_options',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
